name: Python Lint

on:
  pull_request:
    paths:
      - "**/*.py"
      - ".pre-commit-config.yaml"
      - "requirements*.txt"
      - "pyproject.toml"
  push:
    branches: [ main ]
    paths:
      - "**/*.py"
      - ".pre-commit-config.yaml"
      - "requirements*.txt"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Cache pre-commit env
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Run pre-commit (Python hooks)
        env:
          SKIP: terraform_fmt,terraform_validate,terraform_tflint,terraform_docs
        run: pre-commit run --all-files
